services:
  host:
    container_name: host
    build:
      context: host/
      dockerfile: Dockerfile.host
    depends_on:
      - signaling
    ports:
      - 1025:1025
    env_file:
      - .env

  proxy:
    container_name: proxy
    build:
      context: proxy/
      dockerfile: Dockerfile.proxy
    ports:
      - 8080:8080
    depends_on:
      - signaling
    env_file:
      - .env

  signaling:
    container_name: signaling
    build:
      context: signaling/
      dockerfile: Dockerfile.signaling
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env

  database:
    container_name: database
    build:
      context: database/
      dockerfile: Dockerfile.db
    ports:
      - 5432:5432
    volumes:
      - /database/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
