FROM debian:buster

USER root

RUN apt-get -y update ; \
apt-get -y install nginx openssl

RUN mkdir -p /etc/nginx/ssl/

COPY ssl/ft_transcendence_host.crt /etc/nginx/ssl/ft_transcendence_proxy.crt
COPY ssl/ft_transcendence_host.key /etc/nginx/ssl/ft_transcendence_proxy.key

COPY nginx.conf /etc/nginx/conf.d/nginx.conf

COPY init.sh /home/

EXPOSE 8080

CMD ["sh", "/home/init.sh"]